### ISSUE TITLE
autoload.php missing from install

### ISSUE THREAD

**Issue by gsuberland** [echoCTF/echoCTF.RED#438]
I just did a fresh install, following the documentation. I'm getting a bunch of errors due to `require()` calls in the code that reference `vendor/autoload.php`, which doesn't exist.

The error thrown at `docker-compose up` is as follows:

```
PHP Warning: require(/var/www/echoCTF.RED/backend/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/echoCTF.RED/backend/yii on line 14
PHP Fatal error:  require(): Failed opening required '/var/www/echoCTF.RED/backend/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/echoCTF.RED/backend/yii on line 14
```

This is repeated a number of times, and appears whenever trying to follow the next steps after installation such as configuring the email address.

**Comment by proditis** [comment]
Hi there,

Have you run `docker-compose pull` prior to `docker-compose up`?  If not `docker-compose` will try to build the images for you based on the local copy (which requires you run `composer update` under `./frontend/` and `./backend/` folders).

**Comment by gsuberland** [comment]
Thanks for the quick reply. I did run `docker-compose pull` first, but I'm not exactly sure what it did - it appeared to return immediately.

I went through and manually ran `composer update`, which got rid of that error, but the player creation step throws additional errors relating to SSL, and the backend just shows a blank page.

I suspect that something went awry in the early stages. I'm not super familiar with docker - is there a way I can completely clear everything, all packages or whatever included, and start over?

**Comment by proditis** [comment]
Try to do the following
```sh
docker-compose down --rmi all
docker volume rm echoctfred_data-mysql
docker volume rm echoctfred_data-challenges
docker volume rm echoctfred_data-openvpn
```

Once these are done running  `docker-compose pull` and `docker-compose run` again should fix the problem.

**Comment by gsuberland** [comment]
I first tried this:

```
docker container stop $(docker container ls -aq)
docker rm $(docker ps -aq)
docker rmi $(docker images -q)
docker system prune -a --volumes
docker network prune
```

1.8GB of stuff deleted, so that seems like it deleted the lot.

And then a fresh attempt. `docker-compose pull` again returns immediately. `docker-compose up` does all the fetching and building, and hits the same issue - composer isn't being run and the vendor/autoload.php is missing.

Tried again with what you just suggested, although did you mean `docker-compose up` rather than `docker-compose run`?

**Comment by proditis** [comment]
Your commands must've done the trick, they seem to basically do the same tasks.  

Yes you are right, I meant `docker-compose up`, sorry. 

If the problem persists please provide detailed steps you followed along with operating system to try and replicate the problem.

**Comment by gsuberland** [comment]
Same issue still.

- Fresh install of Ubuntu 21.04, all updates installed
- Linux kernel 5.11.0-18-generic x86_64
- Docker 20.10.7 build f0df350 (using the repository as per [docker installation docs](https://docs.docker.com/engine/install/ubuntu/))

Tried with the 0.17 release (wget and unzip) and master branch (git clone).

Commands:

```
cd echoCTF.RED-0.17
sudo docker-compose pull
sudo docker-compose up
```

See attached for the full log.

[echoctfred_docker_install.txt](https://github.com/echoCTF/echoCTF.RED/files/6666210/echoctfred_docker_install.txt)

**Comment by proditis** [comment]
Thanks for the extra details, I'll investigate the issue and get back to you.

**Comment by proditis** [comment]
Ok so based on the attached log it seems that `docker-compose pull` does nothing. Then when you run `docker-compose up`  it fails to find the image locally and tries to build it again.

For reference this is the output from my end
```bash
~/tmp/echoCTF.RED-0.17$ docker-compose pull
Pulling db       ... done
Pulling backend  ... done
Pulling frontend ... done
Pulling vpn      ... done
~/tmp/echoCTF.RED-0.17$ 
```

Can you please attach the output of the following commands?
```bash
cd echoCTF.RED-0.17 
docker-compose version
docker-compose down -v --remove-orphans --rmi all 
docker pull echothrust/echoctf.red-vpn 
docker pull echothrust/echoctf.red-backend
docker pull echothrust/echoctf.red-frontend
docker pull echothrust/echoctf.red-db
docker-compose up
```

**Comment by gsuberland** [comment]
That seems to have gotten it into a much better state - the composer errors are now gone. The functionality seems to work from a very brief play with it. However, there are no images in the `/images/` directory for either web page (8080 or 8082), so there's definitely still something weird with the install.

[echoctfred_output2.txt](https://github.com/echoCTF/echoCTF.RED/files/6671972/echoctfred_output2.txt)

**Comment by proditis** [comment]
Ok that is great. 

Regarding the images, they are left over volumes that i have forgotten to remove :smile: 

Bring the containers down (`docker-compose down`), download the latest `docker-compose.yml` and replace the current one. Once done you can bring the containers back up again.

**Comment by proditis** [comment]
I assume the problem got fixed, so i'm closing this issue. 

If you have any other issues feel free to create a new issue.
